window:
  font:
    name: DroidSans.ttf
    size: 12
    index: 0
    color: "#FFFFFF"
  video-mode:
    width: 640
    height: 480
    bpp: 32
  fps: 1000
  show-fps-rate: 500
  show-fps: true
  interface:
    move-speed: 120
    rotation-speed: 0.333333
    keys-rotation-step: 10
  pointer: textures/crosshair.png
  camera:
    viewer-distance: 1000
    scale: 0.005
    view-limit: 10000
  rendering:
    surface-color: "#5F5F5F"
scene:
  plane-color: "#5F5F5F"
models:
  templates: templates.x
  models: models/models.yml
  models-path: models/
  textures-path: textures/
