window:
  font:
    name: DroidSans.ttf
    size: 12
    index: 0
    color: "#FFFFFF"
  video-mode:
    width: 640
    height: 480
    bpp: 32
  fps: 60
  show-fps-rate: 10
  show-fps: true
  interface:
    move-speed: 120
    rotation-speed: 0.333333
  rasterizer:
    viewer-distance: 1000
  projected-height: 200
scene:
  plane-color: "#FFFFFF"
  templates: templates.x
  models: models/cube.x
  root-frame: Root
