window:
  font:
    name: DroidSans.ttf
    size: 12
    index: 0
    color: "#FFFFFF"
  video-mode:
    width: 640
    height: 480
    bpp: 32
  fps: 60
  show-fps-rate: 10
  show-fps: true
  interface:
    move-speed: 120
    rotation-speed: 0.333333
  pointer: textures/crosshair.png
  camera:
    viewer-distance: 1000
    scale: 0.005
    view-limit: 10000

scene:
  plane-color: "#FFFFFF"
models:
  templates: templates.x
  models: models/models.yml
