#ifndef GRAPH_CONFIG_H_
#define GRAPH_CONFIG_H_

//#define USE_EIGEN
#define NO_GRAB_INPUT
//#define NO_NORMAL_FACE_CLIPPING
#define NO_LIGHTING
#define NO_DRAW_SURFACE
#define AFFINE_TEXTURES

#endif // GRAPH_CONFIG_H_
